import asyncio
from datetime import date, datetime

from anyio import Path
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from daily_insights_api.core.config import Settings, get_settings, is_placeholder_value
from daily_insights_api.core.database import create_engine, create_session_factory
from daily_insights_api.modules.news.llm import DeepSeekClient
from daily_insights_api.modules.news.prompts import load_selection_criteria
from daily_insights_api.modules.news.service import run_news_edition
from daily_insights_api.modules.reports.scheduler import (
    TAIPEI,
    EditionRunner,
    SameDayRetry,
    due_edition,
    maintain_disabled_heartbeat,
    parse_args,
    run_scheduler,
    run_with_heartbeat,
)

HEARTBEAT_PATH = "/tmp/daily-news-heartbeat"
# An unavailable edition (0/5 stories) is retried within the morning window; a
# partial edition is presentable and only regenerated by a manual --once run.
RETRY_POLICY = SameDayRetry(retry_outcomes=frozenset({"unavailable"}))


def build_runner(
    session_factory: async_sessionmaker[AsyncSession],
    client: DeepSeekClient,
    settings: Settings,
    heartbeat: Path,
) -> EditionRunner:
    async def runner(edition_date: date) -> str | None:
        return await run_with_heartbeat(
            lambda target_date: run_news_edition(
                session_factory,
                client,
                target_date,
                allowed_hostnames=settings.news_allowed_hostnames,
                fetch_timeout_seconds=settings.news_fetch_timeout_seconds,
            ),
            edition_date,
            heartbeat,
        )

    return runner


async def main() -> None:
    args = parse_args(description="Run the daily news scheduler")
    settings = get_settings()
    heartbeat = Path(HEARTBEAT_PATH)
    await heartbeat.touch()
    if not settings.daily_news_enabled and not args.once:
        await maintain_disabled_heartbeat(heartbeat)
    api_key = settings.model_api_key
    if (
        api_key is None
        or not api_key.get_secret_value().strip()
        or is_placeholder_value(api_key.get_secret_value())
    ):
        raise SystemExit("model API key is required for daily news")
    engine = create_engine(settings)
    session_factory = create_session_factory(engine)
    client = DeepSeekClient(
        base_url=settings.model_api_base_url,
        api_key=api_key.get_secret_value(),
        model=settings.model_name,
        selection_criteria=load_selection_criteria(),
    )
    runner = build_runner(session_factory, client, settings, heartbeat)
    try:
        now = datetime.now(TAIPEI)
        edition = args.edition_date or (now.date() if args.once else due_edition(now))
        if args.once:
            if edition is None:
                raise SystemExit("no edition is due yet; pass --edition-date")
            await runner(edition)
        else:
            await run_scheduler(runner, now=lambda: datetime.now(TAIPEI), retry=RETRY_POLICY)
    finally:
        await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
