/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAuthenticatedRouteImport } from './routes/$locale/_authenticated'
import { Route as LocaleChangePasswordRouteImport } from './routes/$locale/change-password'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocaleAuthenticatedAdminRouteImport } from './routes/$locale/_authenticated/_admin'
import { Route as LocaleAuthenticatedCustomerRouteImport } from './routes/$locale/_authenticated/_customer'
import { Route as LocaleAuthenticatedBackOfficeRouteImport } from './routes/$locale/_authenticated/back-office'
import { Route as LocaleAdminChangePasswordRouteImport } from './routes/$locale/admin/change-password'
import { Route as LocaleAdminLoginRouteImport } from './routes/$locale/admin/login'
import { Route as LocaleAuthenticatedCustomerAccountRouteImport } from './routes/$locale/_authenticated/_customer/account'
import { Route as LocaleAuthenticatedCustomerPodcastsRouteImport } from './routes/$locale/_authenticated/_customer/podcasts'
import { Route as LocaleAuthenticatedBackOfficePodcastsRouteImport } from './routes/$locale/_authenticated/back-office/podcasts'
import { Route as LocaleAuthenticatedAdminAdminAudioRouteImport } from './routes/$locale/_authenticated/_admin/admin/audio'
import { Route as LocaleAuthenticatedAdminAdminMembersRouteImport } from './routes/$locale/_authenticated/_admin/admin/members'
import { Route as LocaleAuthenticatedCustomerPodcastsIndexRouteImport } from './routes/$locale/_authenticated/_customer/podcasts/index'
import { Route as LocaleAuthenticatedCustomerPodcastsEpisodeIdRouteImport } from './routes/$locale/_authenticated/_customer/podcasts/$episodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthenticatedRoute = LocaleAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleChangePasswordRoute = LocaleChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthenticatedAdminRoute =
  LocaleAuthenticatedAdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => LocaleAuthenticatedRoute,
  } as any)
const LocaleAuthenticatedCustomerRoute =
  LocaleAuthenticatedCustomerRouteImport.update({
    id: '/_customer',
    getParentRoute: () => LocaleAuthenticatedRoute,
  } as any)
const LocaleAuthenticatedBackOfficeRoute =
  LocaleAuthenticatedBackOfficeRouteImport.update({
    id: '/back-office',
    path: '/back-office',
    getParentRoute: () => LocaleAuthenticatedRoute,
  } as any)
const LocaleAdminChangePasswordRoute =
  LocaleAdminChangePasswordRouteImport.update({
    id: '/admin/change-password',
    path: '/admin/change-password',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleAdminLoginRoute = LocaleAdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthenticatedCustomerAccountRoute =
  LocaleAuthenticatedCustomerAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => LocaleAuthenticatedCustomerRoute,
  } as any)
const LocaleAuthenticatedCustomerPodcastsRoute =
  LocaleAuthenticatedCustomerPodcastsRouteImport.update({
    id: '/podcasts',
    path: '/podcasts',
    getParentRoute: () => LocaleAuthenticatedCustomerRoute,
  } as any)
const LocaleAuthenticatedBackOfficePodcastsRoute =
  LocaleAuthenticatedBackOfficePodcastsRouteImport.update({
    id: '/podcasts',
    path: '/podcasts',
    getParentRoute: () => LocaleAuthenticatedBackOfficeRoute,
  } as any)
const LocaleAuthenticatedAdminAdminAudioRoute =
  LocaleAuthenticatedAdminAdminAudioRouteImport.update({
    id: '/admin/audio',
    path: '/admin/audio',
    getParentRoute: () => LocaleAuthenticatedAdminRoute,
  } as any)
const LocaleAuthenticatedAdminAdminMembersRoute =
  LocaleAuthenticatedAdminAdminMembersRouteImport.update({
    id: '/admin/members',
    path: '/admin/members',
    getParentRoute: () => LocaleAuthenticatedAdminRoute,
  } as any)
const LocaleAuthenticatedCustomerPodcastsIndexRoute =
  LocaleAuthenticatedCustomerPodcastsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleAuthenticatedCustomerPodcastsRoute,
  } as any)
const LocaleAuthenticatedCustomerPodcastsEpisodeIdRoute =
  LocaleAuthenticatedCustomerPodcastsEpisodeIdRouteImport.update({
    id: '/$episodeId',
    path: '/$episodeId',
    getParentRoute: () => LocaleAuthenticatedCustomerPodcastsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/change-password': typeof LocaleChangePasswordRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/back-office': typeof LocaleAuthenticatedBackOfficeRouteWithChildren
  '/$locale/admin/change-password': typeof LocaleAdminChangePasswordRoute
  '/$locale/admin/login': typeof LocaleAdminLoginRoute
  '/$locale/account': typeof LocaleAuthenticatedCustomerAccountRoute
  '/$locale/podcasts': typeof LocaleAuthenticatedCustomerPodcastsRouteWithChildren
  '/$locale/back-office/podcasts': typeof LocaleAuthenticatedBackOfficePodcastsRoute
  '/$locale/admin/audio': typeof LocaleAuthenticatedAdminAdminAudioRoute
  '/$locale/admin/members': typeof LocaleAuthenticatedAdminAdminMembersRoute
  '/$locale/podcasts/$episodeId': typeof LocaleAuthenticatedCustomerPodcastsEpisodeIdRoute
  '/$locale/podcasts/': typeof LocaleAuthenticatedCustomerPodcastsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/change-password': typeof LocaleChangePasswordRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/back-office': typeof LocaleAuthenticatedBackOfficeRouteWithChildren
  '/$locale/admin/change-password': typeof LocaleAdminChangePasswordRoute
  '/$locale/admin/login': typeof LocaleAdminLoginRoute
  '/$locale/account': typeof LocaleAuthenticatedCustomerAccountRoute
  '/$locale/back-office/podcasts': typeof LocaleAuthenticatedBackOfficePodcastsRoute
  '/$locale/admin/audio': typeof LocaleAuthenticatedAdminAdminAudioRoute
  '/$locale/admin/members': typeof LocaleAuthenticatedAdminAdminMembersRoute
  '/$locale/podcasts/$episodeId': typeof LocaleAuthenticatedCustomerPodcastsEpisodeIdRoute
  '/$locale/podcasts': typeof LocaleAuthenticatedCustomerPodcastsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/_authenticated': typeof LocaleAuthenticatedRouteWithChildren
  '/$locale/change-password': typeof LocaleChangePasswordRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/_authenticated/_admin': typeof LocaleAuthenticatedAdminRouteWithChildren
  '/$locale/_authenticated/_customer': typeof LocaleAuthenticatedCustomerRouteWithChildren
  '/$locale/_authenticated/back-office': typeof LocaleAuthenticatedBackOfficeRouteWithChildren
  '/$locale/admin/change-password': typeof LocaleAdminChangePasswordRoute
  '/$locale/admin/login': typeof LocaleAdminLoginRoute
  '/$locale/_authenticated/_customer/account': typeof LocaleAuthenticatedCustomerAccountRoute
  '/$locale/_authenticated/_customer/podcasts': typeof LocaleAuthenticatedCustomerPodcastsRouteWithChildren
  '/$locale/_authenticated/back-office/podcasts': typeof LocaleAuthenticatedBackOfficePodcastsRoute
  '/$locale/_authenticated/_admin/admin/audio': typeof LocaleAuthenticatedAdminAdminAudioRoute
  '/$locale/_authenticated/_admin/admin/members': typeof LocaleAuthenticatedAdminAdminMembersRoute
  '/$locale/_authenticated/_customer/podcasts/$episodeId': typeof LocaleAuthenticatedCustomerPodcastsEpisodeIdRoute
  '/$locale/_authenticated/_customer/podcasts/': typeof LocaleAuthenticatedCustomerPodcastsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/change-password'
    | '/$locale/login'
    | '/$locale/'
    | '/$locale/back-office'
    | '/$locale/admin/change-password'
    | '/$locale/admin/login'
    | '/$locale/account'
    | '/$locale/podcasts'
    | '/$locale/back-office/podcasts'
    | '/$locale/admin/audio'
    | '/$locale/admin/members'
    | '/$locale/podcasts/$episodeId'
    | '/$locale/podcasts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/change-password'
    | '/$locale/login'
    | '/$locale/back-office'
    | '/$locale/admin/change-password'
    | '/$locale/admin/login'
    | '/$locale/account'
    | '/$locale/back-office/podcasts'
    | '/$locale/admin/audio'
    | '/$locale/admin/members'
    | '/$locale/podcasts/$episodeId'
    | '/$locale/podcasts'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/_authenticated'
    | '/$locale/change-password'
    | '/$locale/login'
    | '/$locale/'
    | '/$locale/_authenticated/_admin'
    | '/$locale/_authenticated/_customer'
    | '/$locale/_authenticated/back-office'
    | '/$locale/admin/change-password'
    | '/$locale/admin/login'
    | '/$locale/_authenticated/_customer/account'
    | '/$locale/_authenticated/_customer/podcasts'
    | '/$locale/_authenticated/back-office/podcasts'
    | '/$locale/_authenticated/_admin/admin/audio'
    | '/$locale/_authenticated/_admin/admin/members'
    | '/$locale/_authenticated/_customer/podcasts/$episodeId'
    | '/$locale/_authenticated/_customer/podcasts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_authenticated': {
      id: '/$locale/_authenticated'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthenticatedRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/change-password': {
      id: '/$locale/change-password'
      path: '/change-password'
      fullPath: '/$locale/change-password'
      preLoaderRoute: typeof LocaleChangePasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_authenticated/_admin': {
      id: '/$locale/_authenticated/_admin'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthenticatedAdminRouteImport
      parentRoute: typeof LocaleAuthenticatedRoute
    }
    '/$locale/_authenticated/_customer': {
      id: '/$locale/_authenticated/_customer'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthenticatedCustomerRouteImport
      parentRoute: typeof LocaleAuthenticatedRoute
    }
    '/$locale/_authenticated/back-office': {
      id: '/$locale/_authenticated/back-office'
      path: '/back-office'
      fullPath: '/$locale/back-office'
      preLoaderRoute: typeof LocaleAuthenticatedBackOfficeRouteImport
      parentRoute: typeof LocaleAuthenticatedRoute
    }
    '/$locale/admin/change-password': {
      id: '/$locale/admin/change-password'
      path: '/admin/change-password'
      fullPath: '/$locale/admin/change-password'
      preLoaderRoute: typeof LocaleAdminChangePasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/login': {
      id: '/$locale/admin/login'
      path: '/admin/login'
      fullPath: '/$locale/admin/login'
      preLoaderRoute: typeof LocaleAdminLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_authenticated/_customer/account': {
      id: '/$locale/_authenticated/_customer/account'
      path: '/account'
      fullPath: '/$locale/account'
      preLoaderRoute: typeof LocaleAuthenticatedCustomerAccountRouteImport
      parentRoute: typeof LocaleAuthenticatedCustomerRoute
    }
    '/$locale/_authenticated/_customer/podcasts': {
      id: '/$locale/_authenticated/_customer/podcasts'
      path: '/podcasts'
      fullPath: '/$locale/podcasts'
      preLoaderRoute: typeof LocaleAuthenticatedCustomerPodcastsRouteImport
      parentRoute: typeof LocaleAuthenticatedCustomerRoute
    }
    '/$locale/_authenticated/back-office/podcasts': {
      id: '/$locale/_authenticated/back-office/podcasts'
      path: '/podcasts'
      fullPath: '/$locale/back-office/podcasts'
      preLoaderRoute: typeof LocaleAuthenticatedBackOfficePodcastsRouteImport
      parentRoute: typeof LocaleAuthenticatedBackOfficeRoute
    }
    '/$locale/_authenticated/_admin/admin/audio': {
      id: '/$locale/_authenticated/_admin/admin/audio'
      path: '/admin/audio'
      fullPath: '/$locale/admin/audio'
      preLoaderRoute: typeof LocaleAuthenticatedAdminAdminAudioRouteImport
      parentRoute: typeof LocaleAuthenticatedAdminRoute
    }
    '/$locale/_authenticated/_admin/admin/members': {
      id: '/$locale/_authenticated/_admin/admin/members'
      path: '/admin/members'
      fullPath: '/$locale/admin/members'
      preLoaderRoute: typeof LocaleAuthenticatedAdminAdminMembersRouteImport
      parentRoute: typeof LocaleAuthenticatedAdminRoute
    }
    '/$locale/_authenticated/_customer/podcasts/': {
      id: '/$locale/_authenticated/_customer/podcasts/'
      path: '/'
      fullPath: '/$locale/podcasts/'
      preLoaderRoute: typeof LocaleAuthenticatedCustomerPodcastsIndexRouteImport
      parentRoute: typeof LocaleAuthenticatedCustomerPodcastsRoute
    }
    '/$locale/_authenticated/_customer/podcasts/$episodeId': {
      id: '/$locale/_authenticated/_customer/podcasts/$episodeId'
      path: '/$episodeId'
      fullPath: '/$locale/podcasts/$episodeId'
      preLoaderRoute: typeof LocaleAuthenticatedCustomerPodcastsEpisodeIdRouteImport
      parentRoute: typeof LocaleAuthenticatedCustomerPodcastsRoute
    }
  }
}

interface LocaleAuthenticatedAdminRouteChildren {
  LocaleAuthenticatedAdminAdminAudioRoute: typeof LocaleAuthenticatedAdminAdminAudioRoute
  LocaleAuthenticatedAdminAdminMembersRoute: typeof LocaleAuthenticatedAdminAdminMembersRoute
}

const LocaleAuthenticatedAdminRouteChildren: LocaleAuthenticatedAdminRouteChildren =
  {
    LocaleAuthenticatedAdminAdminAudioRoute:
      LocaleAuthenticatedAdminAdminAudioRoute,
    LocaleAuthenticatedAdminAdminMembersRoute:
      LocaleAuthenticatedAdminAdminMembersRoute,
  }

const LocaleAuthenticatedAdminRouteWithChildren =
  LocaleAuthenticatedAdminRoute._addFileChildren(
    LocaleAuthenticatedAdminRouteChildren,
  )

interface LocaleAuthenticatedCustomerPodcastsRouteChildren {
  LocaleAuthenticatedCustomerPodcastsEpisodeIdRoute: typeof LocaleAuthenticatedCustomerPodcastsEpisodeIdRoute
  LocaleAuthenticatedCustomerPodcastsIndexRoute: typeof LocaleAuthenticatedCustomerPodcastsIndexRoute
}

const LocaleAuthenticatedCustomerPodcastsRouteChildren: LocaleAuthenticatedCustomerPodcastsRouteChildren =
  {
    LocaleAuthenticatedCustomerPodcastsEpisodeIdRoute:
      LocaleAuthenticatedCustomerPodcastsEpisodeIdRoute,
    LocaleAuthenticatedCustomerPodcastsIndexRoute:
      LocaleAuthenticatedCustomerPodcastsIndexRoute,
  }

const LocaleAuthenticatedCustomerPodcastsRouteWithChildren =
  LocaleAuthenticatedCustomerPodcastsRoute._addFileChildren(
    LocaleAuthenticatedCustomerPodcastsRouteChildren,
  )

interface LocaleAuthenticatedCustomerRouteChildren {
  LocaleAuthenticatedCustomerAccountRoute: typeof LocaleAuthenticatedCustomerAccountRoute
  LocaleAuthenticatedCustomerPodcastsRoute: typeof LocaleAuthenticatedCustomerPodcastsRouteWithChildren
}

const LocaleAuthenticatedCustomerRouteChildren: LocaleAuthenticatedCustomerRouteChildren =
  {
    LocaleAuthenticatedCustomerAccountRoute:
      LocaleAuthenticatedCustomerAccountRoute,
    LocaleAuthenticatedCustomerPodcastsRoute:
      LocaleAuthenticatedCustomerPodcastsRouteWithChildren,
  }

const LocaleAuthenticatedCustomerRouteWithChildren =
  LocaleAuthenticatedCustomerRoute._addFileChildren(
    LocaleAuthenticatedCustomerRouteChildren,
  )

interface LocaleAuthenticatedBackOfficeRouteChildren {
  LocaleAuthenticatedBackOfficePodcastsRoute: typeof LocaleAuthenticatedBackOfficePodcastsRoute
}

const LocaleAuthenticatedBackOfficeRouteChildren: LocaleAuthenticatedBackOfficeRouteChildren =
  {
    LocaleAuthenticatedBackOfficePodcastsRoute:
      LocaleAuthenticatedBackOfficePodcastsRoute,
  }

const LocaleAuthenticatedBackOfficeRouteWithChildren =
  LocaleAuthenticatedBackOfficeRoute._addFileChildren(
    LocaleAuthenticatedBackOfficeRouteChildren,
  )

interface LocaleAuthenticatedRouteChildren {
  LocaleAuthenticatedAdminRoute: typeof LocaleAuthenticatedAdminRouteWithChildren
  LocaleAuthenticatedCustomerRoute: typeof LocaleAuthenticatedCustomerRouteWithChildren
  LocaleAuthenticatedBackOfficeRoute: typeof LocaleAuthenticatedBackOfficeRouteWithChildren
}

const LocaleAuthenticatedRouteChildren: LocaleAuthenticatedRouteChildren = {
  LocaleAuthenticatedAdminRoute: LocaleAuthenticatedAdminRouteWithChildren,
  LocaleAuthenticatedCustomerRoute:
    LocaleAuthenticatedCustomerRouteWithChildren,
  LocaleAuthenticatedBackOfficeRoute:
    LocaleAuthenticatedBackOfficeRouteWithChildren,
}

const LocaleAuthenticatedRouteWithChildren =
  LocaleAuthenticatedRoute._addFileChildren(LocaleAuthenticatedRouteChildren)

interface LocaleRouteChildren {
  LocaleAuthenticatedRoute: typeof LocaleAuthenticatedRouteWithChildren
  LocaleChangePasswordRoute: typeof LocaleChangePasswordRoute
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAdminChangePasswordRoute: typeof LocaleAdminChangePasswordRoute
  LocaleAdminLoginRoute: typeof LocaleAdminLoginRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAuthenticatedRoute: LocaleAuthenticatedRouteWithChildren,
  LocaleChangePasswordRoute: LocaleChangePasswordRoute,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAdminChangePasswordRoute: LocaleAdminChangePasswordRoute,
  LocaleAdminLoginRoute: LocaleAdminLoginRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
