"""Public provider-neutral data-source contracts."""

from daily_insights_api.modules.data_sources import (
    DailyBar,
    DailyBarQuery,
    DataSourceAuthenticationError,
    DataSourceContractError,
    DataSourceError,
    DataSourceTransientError,
    InstitutionalFlowDay,
    InstitutionalFlowResult,
    InstitutionalStockFlow,
    InstitutionalStockFlowResult,
    Instrument,
    InstrumentQuery,
    PageInfo,
    Provenance,
    ProviderPage,
    UnsupportedMarketError,
)
from daily_insights_api.modules.data_sources.dto import MarketCode
from daily_insights_api.modules.data_sources.provider import (
    InstitutionalFlowProvider,
    MarketDataProvider,
)
from daily_insights_api.modules.data_sources.twelve_data import (
    TWELVE_DATA_CONTRACT_HASH,
    TWELVE_DATA_CONTRACT_VERSION,
    EodResult,
    EodsResult,
    QuoteResult,
    QuotesResult,
    RetryPolicy,
    TwelveDataAdapter,
    TwelveDataTransport,
)
from daily_insights_api.modules.data_sources.twse import (
    BFI82U_ENDPOINT,
    T86_ENDPOINTS,
    TWSE_CONTRACT_HASH,
    TWSE_CONTRACT_VERSION,
    TwseAdapter,
    TwseTransport,
)
from daily_insights_api.modules.data_sources.yfinance import (
    TRACKED_INDICES,
    IndexSymbol,
    YfinanceAdapter,
    YfinanceDailyBars,
)

__all__ = [
    "BFI82U_ENDPOINT",
    "T86_ENDPOINTS",
    "TRACKED_INDICES",
    "TWELVE_DATA_CONTRACT_HASH",
    "TWELVE_DATA_CONTRACT_VERSION",
    "TWSE_CONTRACT_HASH",
    "TWSE_CONTRACT_VERSION",
    "DailyBar",
    "DailyBarQuery",
    "DataSourceAuthenticationError",
    "DataSourceContractError",
    "DataSourceError",
    "DataSourceTransientError",
    "EodResult",
    "EodsResult",
    "IndexSymbol",
    "InstitutionalFlowDay",
    "InstitutionalFlowProvider",
    "InstitutionalFlowResult",
    "InstitutionalStockFlow",
    "InstitutionalStockFlowResult",
    "Instrument",
    "InstrumentQuery",
    "MarketCode",
    "MarketDataProvider",
    "PageInfo",
    "Provenance",
    "ProviderPage",
    "QuoteResult",
    "QuotesResult",
    "RetryPolicy",
    "TwelveDataAdapter",
    "TwelveDataTransport",
    "TwseAdapter",
    "TwseTransport",
    "UnsupportedMarketError",
    "YfinanceAdapter",
    "YfinanceDailyBars",
]
