"""Public provider-neutral data-source contracts."""

from daily_insights_api.modules.data_sources import (
    DailyBar,
    DailyBarQuery,
    DataSourceAuthenticationError,
    DataSourceContractError,
    DataSourceError,
    DataSourceTransientError,
    Instrument,
    InstrumentQuery,
    PageInfo,
    Provenance,
    ProviderPage,
    UnsupportedMarketError,
)
from daily_insights_api.modules.data_sources.dto import MarketCode
from daily_insights_api.modules.data_sources.provider import (
    MarketDataProvider,
)
from daily_insights_api.modules.data_sources.twelve_data import (
    TWELVE_DATA_CONTRACT_HASH,
    TWELVE_DATA_CONTRACT_VERSION,
    CompletedPriceResult,
    CompletedPricesResult,
    EodResult,
    EodsResult,
    RetryPolicy,
    TwelveDataAdapter,
    TwelveDataTransport,
)
from daily_insights_api.modules.data_sources.twse import (
    BFI82U_ENDPOINT,
    T86_ENDPOINT,
    TAIEX_CONTRACT_VERSION,
    TWSE_CONTRACT_HASH,
    TWSE_CONTRACT_VERSION,
    TaiexDailyBar,
    TaiexDailyBars,
    TwseAdapter,
    TwseMarketFlow,
    TwseMarketFlows,
    TwseStockFlow,
    TwseStockFlows,
)
from daily_insights_api.modules.data_sources.yfinance import (
    TRACKED_INDICES,
    IndexSymbol,
    YfinanceAdapter,
    YfinanceDailyBars,
)
from daily_insights_api.modules.data_sources.yfinance.adapter import YFINANCE_CONTRACT_VERSION

__all__ = [
    "BFI82U_ENDPOINT",
    "T86_ENDPOINT",
    "TAIEX_CONTRACT_VERSION",
    "TRACKED_INDICES",
    "TWELVE_DATA_CONTRACT_HASH",
    "TWELVE_DATA_CONTRACT_VERSION",
    "TWSE_CONTRACT_HASH",
    "TWSE_CONTRACT_VERSION",
    "YFINANCE_CONTRACT_VERSION",
    "CompletedPriceResult",
    "CompletedPricesResult",
    "DailyBar",
    "DailyBarQuery",
    "DataSourceAuthenticationError",
    "DataSourceContractError",
    "DataSourceError",
    "DataSourceTransientError",
    "EodResult",
    "EodsResult",
    "IndexSymbol",
    "Instrument",
    "InstrumentQuery",
    "MarketCode",
    "MarketDataProvider",
    "PageInfo",
    "Provenance",
    "ProviderPage",
    "RetryPolicy",
    "TaiexDailyBar",
    "TaiexDailyBars",
    "TwelveDataAdapter",
    "TwelveDataTransport",
    "TwseAdapter",
    "TwseMarketFlow",
    "TwseMarketFlows",
    "TwseStockFlow",
    "TwseStockFlows",
    "UnsupportedMarketError",
    "YfinanceAdapter",
    "YfinanceDailyBars",
]
