/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/admin/audit-events": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Audit Events */
    get: operations["list_audit_events_api_admin_audit_events_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/internal-users": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Internal Users */
    get: operations["list_internal_users_api_admin_internal_users_get"]
    put?: never
    /** Create Internal User */
    post: operations["create_internal_user_api_admin_internal_users_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/organizations": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Organizations */
    get: operations["list_organizations_api_admin_organizations_get"]
    put?: never
    /** Create Organization */
    post: operations["create_organization_api_admin_organizations_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/organizations/{organization_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Organization */
    get: operations["get_organization_api_admin_organizations__organization_id__get"]
    put?: never
    post?: never
    /** Archive Organization */
    delete: operations["archive_organization_api_admin_organizations__organization_id__delete"]
    options?: never
    head?: never
    /** Update Organization */
    patch: operations["update_organization_api_admin_organizations__organization_id__patch"]
    trace?: never
  }
  "/api/admin/organizations/{organization_id}/markets": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Organization Markets */
    get: operations["list_organization_markets_api_admin_organizations__organization_id__markets_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/organizations/{organization_id}/markets/{market_code}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Set Organization Market */
    put: operations["set_organization_market_api_admin_organizations__organization_id__markets__market_code__put"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/organizations/{organization_id}/members": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Members */
    get: operations["list_members_api_admin_organizations__organization_id__members_get"]
    put?: never
    /** Create Member */
    post: operations["create_member_api_admin_organizations__organization_id__members_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/organizations/{organization_id}/members/{user_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove Member */
    delete: operations["remove_member_api_admin_organizations__organization_id__members__user_id__delete"]
    options?: never
    head?: never
    /** Update Member */
    patch: operations["update_member_api_admin_organizations__organization_id__members__user_id__patch"]
    trace?: never
  }
  "/api/admin/podcasts": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Admin List */
    get: operations["admin_podcasts_list"]
    put?: never
    /** Admin Create */
    post: operations["admin_podcasts_create"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/podcasts/uploads": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Admin Upload */
    post: operations["admin_podcasts_upload"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/podcasts/{episode_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Admin Update */
    put: operations["admin_podcasts_update"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/podcasts/{episode_id}/audio-imports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Admin Import Audio */
    post: operations["admin_podcasts_import_audio"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/podcasts/{episode_id}/publish": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Admin Publish */
    post: operations["admin_podcasts_publish"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/podcasts/{episode_id}/unpublish": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Admin Unpublish */
    post: operations["admin_podcasts_unpublish"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/change-password": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Change Password */
    post: operations["auth_change_password"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/csrf": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Refresh Csrf Token
     * @description Rotate a CSRF token using only the authenticated same-site session cookie.
     *
     *     This endpoint deliberately does not require the previous CSRF token: it is
     *     the recovery path after a reload. The strict SameSite session cookie and
     *     same-origin browser transport remain the request boundary.
     */
    post: operations["auth_rotate_csrf_token"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login */
    post: operations["auth_login"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations["auth_logout"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations["auth_get_current_user"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/health/live": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Live */
    get: operations["live_api_health_live_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/health/ready": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Ready */
    get: operations["ready_api_health_ready_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/markets": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Visible Markets */
    get: operations["list_visible_markets_api_markets_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/podcasts": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Customer List */
    get: operations["podcasts_list"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/podcasts/{episode_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Customer Detail */
    get: operations["podcasts_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/podcasts/{episode_id}/audio-url": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Customer Audio Url */
    post: operations["podcasts_create_audio_url"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/reports": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Latest Reports */
    get: operations["list_latest_reports_api_reports_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/reports/{market_code}/latest": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Latest Report */
    get: operations["get_latest_report_api_reports__market_code__latest_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AuditEventResponse */
    AuditEventResponse: {
      /** Action */
      action: string
      /** Actor User Id */
      actor_user_id: string | null
      /** After */
      after: {
        [key: string]: unknown
      } | null
      /** Before */
      before: {
        [key: string]: unknown
      } | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Organization Id */
      organization_id: string | null
      /** Reason */
      reason: string | null
      /** Request Id */
      request_id: string | null
      /** Target Id */
      target_id: string
      /** Target Type */
      target_type: string
    }
    /** AuthenticationResponse */
    AuthenticationResponse: {
      /** Csrf Token */
      csrf_token: string
      user: components["schemas"]["UserResponse"]
    }
    /** Body_admin_podcasts_upload */
    Body_admin_podcasts_upload: {
      /**
       * Confirm Replacement
       * @default false
       */
      confirm_replacement: boolean
      /** En */
      en?: string | null
      /**
       * Expected Versions
       * @default {}
       */
      expected_versions: string
      /**
       * Reason
       * @enum {string}
       */
      reason: "initial_upload" | "update_file" | "other"
      /**
       * Trading Date
       * Format: date
       */
      trading_date: string
      /** Zh Hans */
      zh_hans?: string | null
      /** Zh Hant */
      zh_hant?: string | null
    }
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string
      /** New Password */
      new_password: string
    }
    /** ChartData */
    ChartData: {
      /** Id */
      id: string
      /** Series */
      series: components["schemas"]["ChartSeries"][]
      /** Unit Code */
      unit_code: string
    }
    /** ChartPoint */
    ChartPoint: {
      /** Value */
      value: string | null
      /** X */
      x: string
    }
    /** ChartSeries */
    ChartSeries: {
      /** Id */
      id: string
      /** Points */
      points: components["schemas"]["ChartPoint"][]
    }
    /** ComponentHealth */
    ComponentHealth: {
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "unhealthy"
    }
    /** CsrfTokenResponse */
    CsrfTokenResponse: {
      /** Csrf Token */
      csrf_token: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string
    }
    /** InternalUserCreate */
    InternalUserCreate: {
      /** Display Name */
      display_name: string
      /** Email */
      email: string
      /** Reason */
      reason: string
      system_role: components["schemas"]["SystemRole"]
    }
    /** InternalUserResponse */
    InternalUserResponse: {
      /** Display Name */
      display_name: string
      /** Email */
      email: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Must Change Password */
      must_change_password: boolean
      status: components["schemas"]["UserStatus"]
      system_role: components["schemas"]["SystemRole"]
    }
    /** LocalizedElementText */
    LocalizedElementText: {
      /** Description */
      description?: string | null
      /** Series Labels */
      series_labels?: {
        [key: string]: string
      }
      /** Title */
      title: string
      /** Unit Label */
      unit_label?: string | null
    }
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string
      /** Password */
      password: string
    }
    /** MarketPolicyUpdate */
    MarketPolicyUpdate: {
      /** Contract Reference */
      contract_reference: string
      /** Is Visible */
      is_visible: boolean
      /** Reason */
      reason: string
    }
    /** MarketResponse */
    MarketResponse: {
      /** Code */
      code: string
      /** Is Visible */
      is_visible: boolean
      /** Name En */
      name_en: string
      /** Name Zh Hans */
      name_zh_hans: string
      /** Name Zh Hant */
      name_zh_hant: string
    }
    /** MemberCreate */
    MemberCreate: {
      /** Display Name */
      display_name: string
      /** Email */
      email: string
      /** Reason */
      reason: string
    }
    /** MemberResponse */
    MemberResponse: {
      /** Display Name */
      display_name: string
      /** Email */
      email: string
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string
      /**
       * Membership Id
       * Format: uuid
       */
      membership_id: string
      /** Must Change Password */
      must_change_password: boolean
      status: components["schemas"]["UserStatus"]
      /**
       * User Id
       * Format: uuid
       */
      user_id: string
    }
    /** MemberUpdate */
    MemberUpdate: {
      /** Display Name */
      display_name?: string | null
      /** Reason */
      reason: string
      status?: components["schemas"]["UserStatus"] | null
    }
    /** MetricBlock */
    MetricBlock: {
      /** Caveat */
      caveat?: string | null
      /** Id */
      id: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "metric"
      /** Metrics */
      metrics: components["schemas"]["MetricItem"][]
      /** Source As Of */
      source_as_of: string | null
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "missing" | "error"
    }
    /** MetricItem */
    MetricItem: {
      /** Change */
      change?: string | null
      /** Id */
      id: string
      /** Unit Code */
      unit_code: string
      /** Value */
      value: string | null
    }
    /** MetricValue */
    MetricValue: {
      /** Id */
      id: string
      /** Unit Code */
      unit_code: string
      /** Value */
      value: string
    }
    /** OrganizationCreate */
    OrganizationCreate: {
      /** Contract Reference */
      contract_reference: string
      /** Name */
      name: string
      /** Reason */
      reason: string
      /** Seat Limit */
      seat_limit: number
      /** Slug */
      slug: string
    }
    /** OrganizationResponse */
    OrganizationResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Seat Count */
      seat_count: number
      /** Seat Limit */
      seat_limit: number
      /** Slug */
      slug: string
      status: components["schemas"]["OrganizationStatus"]
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
    }
    /**
     * OrganizationStatus
     * @enum {string}
     */
    OrganizationStatus: "active" | "suspended" | "archived"
    /** OrganizationUpdate */
    OrganizationUpdate: {
      /** Contract Reference */
      contract_reference: string
      /** Name */
      name?: string | null
      /** Reason */
      reason: string
      /** Seat Limit */
      seat_limit?: number | null
      /** Slug */
      slug?: string | null
      status?: components["schemas"]["OrganizationStatus"] | null
    }
    /** PodcastAudioImportRequest */
    PodcastAudioImportRequest: {
      /**
       * Confirm Replacement
       * @default false
       */
      confirm_replacement: boolean
      /** Expected Current Version */
      expected_current_version?: number | null
      /** Expected Mime Type */
      expected_mime_type: string
      /**
       * Locale
       * @default zh-hant
       * @enum {string}
       */
      locale: "zh-hant" | "zh-hans" | "en"
      /** Reason */
      reason: string
      /** Source Bucket */
      source_bucket: string
      /** Source Key */
      source_key: string
    }
    /** PodcastAudioPlaybackResponse */
    PodcastAudioPlaybackResponse: {
      /**
       * Asset Id
       * Format: uuid
       */
      asset_id: string
      /**
       * Episode Id
       * Format: uuid
       */
      episode_id: string
      /** Expires In Seconds */
      expires_in_seconds: number
      /**
       * Requested Locale
       * @enum {string}
       */
      requested_locale: "zh-hant" | "zh-hans" | "en"
      /**
       * Resolved Locale
       * @enum {string}
       */
      resolved_locale: "zh-hant" | "zh-hans" | "en"
      /** Url */
      url: string
    }
    /** PodcastAudioVariantResponse */
    PodcastAudioVariantResponse: {
      /**
       * Asset Id
       * Format: uuid
       */
      asset_id: string
      /** Is Active */
      is_active: boolean
      /**
       * Locale
       * @enum {string}
       */
      locale: "zh-hant" | "zh-hans" | "en"
      /** Version */
      version: number
    }
    /** PodcastEpisodeAdminResponse */
    PodcastEpisodeAdminResponse: {
      /** Audio Variants */
      audio_variants: components["schemas"]["PodcastAudioVariantResponse"][]
      /** Cover Asset Id */
      cover_asset_id: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Metadata */
      metadata: components["schemas"]["PodcastMetadata"][]
      /** Published At */
      published_at: string | null
      /**
       * Status
       * @enum {string}
       */
      status: "draft" | "published"
      /**
       * Trading Date
       * Format: date
       */
      trading_date: string
      /** Version */
      version: number
    }
    /** PodcastEpisodeCreate */
    PodcastEpisodeCreate: {
      metadata: components["schemas"]["PodcastMetadataSet"]
      /** Reason */
      reason: string
      /**
       * Trading Date
       * Format: date
       */
      trading_date: string
    }
    /** PodcastEpisodeDetailResponse */
    PodcastEpisodeDetailResponse: {
      /** Cover Asset Id */
      cover_asset_id: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Locale
       * @enum {string}
       */
      locale: "zh-hant" | "zh-hans" | "en"
      /**
       * Published At
       * Format: date-time
       */
      published_at: string
      /** Summary */
      summary: string
      /** Title */
      title: string
      /**
       * Trading Date
       * Format: date
       */
      trading_date: string
    }
    /** PodcastEpisodeSummaryResponse */
    PodcastEpisodeSummaryResponse: {
      /** Cover Asset Id */
      cover_asset_id: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Locale
       * @enum {string}
       */
      locale: "zh-hant" | "zh-hans" | "en"
      /** Summary */
      summary: string
      /** Title */
      title: string
      /**
       * Trading Date
       * Format: date
       */
      trading_date: string
    }
    /** PodcastEpisodeUpdate */
    PodcastEpisodeUpdate: {
      /** Expected Version */
      expected_version: number
      metadata: components["schemas"]["PodcastMetadataSet"]
      /** Reason */
      reason: string
    }
    /** PodcastMetadata */
    PodcastMetadata: {
      /**
       * Locale
       * @enum {string}
       */
      locale: "zh-hant" | "zh-hans" | "en"
      /** Summary */
      summary: string
      /** Title */
      title: string
    }
    /** PodcastMetadataSet */
    PodcastMetadataSet: {
      /** Values */
      values: components["schemas"]["PodcastMetadata"][]
    }
    /** PodcastPublicationRequest */
    PodcastPublicationRequest: {
      /** Expected Version */
      expected_version: number
    }
    /** PresentationContract */
    PresentationContract: {
      /** Labels */
      labels: {
        [key: string]: components["schemas"]["LocalizedElementText"]
      }
      /**
       * Locale
       * @enum {string}
       */
      locale: "zh-hant" | "zh-hans" | "en"
      /** Schema Version */
      schema_version: string
      /** Summary */
      summary?: string | null
      /** Title */
      title: string
    }
    /** ProvisionedInternalUserResponse */
    ProvisionedInternalUserResponse: {
      /** Display Name */
      display_name: string
      /** Email */
      email: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Must Change Password */
      must_change_password: boolean
      status: components["schemas"]["UserStatus"]
      system_role: components["schemas"]["SystemRole"]
      /** Temporary Password */
      temporary_password: string
    }
    /** ProvisionedMemberResponse */
    ProvisionedMemberResponse: {
      /** Display Name */
      display_name: string
      /** Email */
      email: string
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string
      /**
       * Membership Id
       * Format: uuid
       */
      membership_id: string
      /** Must Change Password */
      must_change_password: boolean
      status: components["schemas"]["UserStatus"]
      /** Temporary Password */
      temporary_password: string
      /**
       * User Id
       * Format: uuid
       */
      user_id: string
    }
    /**
     * PublicationContent
     * @description Locale-neutral application-owned values.
     *
     *     Decimal is intentionally retained in memory and serialized as a JSON string
     *     by Pydantic. This avoids locale-specific formatting and binary float loss.
     */
    PublicationContent: {
      /** As Of */
      as_of: string | null
      /**
       * Blocks
       * @default []
       */
      blocks: (
        | components["schemas"]["MetricBlock"]
        | components["schemas"]["TableBlock"]
        | components["schemas"]["SeriesBlock"]
      )[]
      /** Caveat */
      caveat?: string | null
      /**
       * Charts
       * @default []
       */
      charts: components["schemas"]["ChartData"][]
      /** Market Code */
      market_code: string
      /**
       * Metrics
       * @default []
       */
      metrics: components["schemas"]["MetricValue"][]
      /** Schema Version */
      schema_version: string
      /**
       * Status
       * @default complete
       * @enum {string}
       */
      status: "complete" | "partial" | "unavailable"
    }
    /** ReadinessReport */
    ReadinessReport: {
      /** Components */
      components: {
        [key: string]: components["schemas"]["ComponentHealth"]
      }
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "unhealthy"
    }
    /** ReportDetailResponse */
    ReportDetailResponse: {
      content: components["schemas"]["PublicationContent"]
      /**
       * Edition Date
       * Format: date
       */
      edition_date: string
      /**
       * Locale
       * @enum {string}
       */
      locale: "zh-hant" | "zh-hans" | "en"
      /** Manifest Hash */
      manifest_hash: string
      /** Manifest Version */
      manifest_version: string
      /** Market Code */
      market_code: string
      presentation: components["schemas"]["PresentationContract"]
      /**
       * Publication Id
       * Format: uuid
       */
      publication_id: string
      /**
       * Published At
       * Format: date-time
       */
      published_at: string
      /** Report Key */
      report_key: string
      /** Revision */
      revision: number
      /** Source As Of */
      source_as_of: string | null
      /** Stale */
      stale: boolean
      /** Stale Reason */
      stale_reason: string | null
      /**
       * Status
       * @enum {string}
       */
      status: "complete" | "partial" | "unavailable"
      /** Summary */
      summary: string | null
      /** Title */
      title: string
    }
    /** ReportSummaryResponse */
    ReportSummaryResponse: {
      /**
       * Edition Date
       * Format: date
       */
      edition_date: string
      /**
       * Locale
       * @enum {string}
       */
      locale: "zh-hant" | "zh-hans" | "en"
      /** Market Code */
      market_code: string
      /**
       * Publication Id
       * Format: uuid
       */
      publication_id: string
      /**
       * Published At
       * Format: date-time
       */
      published_at: string
      /** Report Key */
      report_key: string
      /** Revision */
      revision: number
      /** Source As Of */
      source_as_of: string | null
      /** Stale */
      stale: boolean
      /** Stale Reason */
      stale_reason: string | null
      /**
       * Status
       * @enum {string}
       */
      status: "complete" | "partial" | "unavailable"
      /** Summary */
      summary: string | null
      /** Title */
      title: string
    }
    /** SeriesBlock */
    SeriesBlock: {
      /** Caveat */
      caveat?: string | null
      /** Id */
      id: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "series"
      /** Series */
      series: components["schemas"]["ChartSeries"][]
      /** Source As Of */
      source_as_of: string | null
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "missing" | "error"
      /** Unit Code */
      unit_code: string
    }
    /**
     * SystemRole
     * @enum {string}
     */
    SystemRole: "admin" | "asset_manager" | "org_member"
    /** TableBlock */
    TableBlock: {
      /** Caveat */
      caveat?: string | null
      /** Columns */
      columns: components["schemas"]["TableColumn"][]
      /** Id */
      id: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "table"
      /** Rows */
      rows: (components["schemas"]["TableCell"] | null)[][]
      /** Source As Of */
      source_as_of: string | null
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "missing" | "error"
    }
    /** TableCell */
    TableCell: {
      /** Text */
      text?: string | null
      /** Value */
      value?: string | null
    }
    /** TableColumn */
    TableColumn: {
      /** Id */
      id: string
      /** Unit Code */
      unit_code?: string | null
    }
    /** UserResponse */
    UserResponse: {
      /** Display Name */
      display_name: string
      /** Email */
      email: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Must Change Password */
      must_change_password: boolean
      /** Organization Id */
      organization_id: string | null
      status: components["schemas"]["UserStatus"]
      system_role: components["schemas"]["SystemRole"]
    }
    /**
     * UserStatus
     * @enum {string}
     */
    UserStatus: "invited" | "active" | "suspended"
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_audit_events_api_admin_audit_events_get: {
    parameters: {
      query?: {
        organization_id?: string | null
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AuditEventResponse"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_internal_users_api_admin_internal_users_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["InternalUserResponse"][]
        }
      }
    }
  }
  create_internal_user_api_admin_internal_users_post: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InternalUserCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ProvisionedInternalUserResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_organizations_api_admin_organizations_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OrganizationResponse"][]
        }
      }
    }
  }
  create_organization_api_admin_organizations_post: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganizationCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OrganizationResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_organization_api_admin_organizations__organization_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        organization_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OrganizationResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  archive_organization_api_admin_organizations__organization_id__delete: {
    parameters: {
      query: {
        reason: string
        contract_reference: string
      }
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path: {
        organization_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_organization_api_admin_organizations__organization_id__patch: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path: {
        organization_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganizationUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OrganizationResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_organization_markets_api_admin_organizations__organization_id__markets_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        organization_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MarketResponse"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  set_organization_market_api_admin_organizations__organization_id__markets__market_code__put: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path: {
        organization_id: string
        market_code: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["MarketPolicyUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MarketResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_members_api_admin_organizations__organization_id__members_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        organization_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MemberResponse"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  create_member_api_admin_organizations__organization_id__members_post: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path: {
        organization_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ProvisionedMemberResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  remove_member_api_admin_organizations__organization_id__members__user_id__delete: {
    parameters: {
      query: {
        reason: string
      }
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path: {
        organization_id: string
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  update_member_api_admin_organizations__organization_id__members__user_id__patch: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path: {
        organization_id: string
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MemberResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  admin_podcasts_list: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PodcastEpisodeAdminResponse"][]
        }
      }
    }
  }
  admin_podcasts_create: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PodcastEpisodeCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PodcastEpisodeAdminResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  admin_podcasts_upload: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_admin_podcasts_upload"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PodcastEpisodeAdminResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  admin_podcasts_update: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path: {
        episode_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PodcastEpisodeUpdate"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PodcastEpisodeAdminResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  admin_podcasts_import_audio: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path: {
        episode_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PodcastAudioImportRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PodcastEpisodeAdminResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  admin_podcasts_publish: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path: {
        episode_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PodcastPublicationRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PodcastEpisodeAdminResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  admin_podcasts_unpublish: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path: {
        episode_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PodcastPublicationRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PodcastEpisodeAdminResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  auth_change_password: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AuthenticationResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  auth_rotate_csrf_token: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["CsrfTokenResponse"]
        }
      }
    }
  }
  auth_login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["AuthenticationResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  auth_logout: {
    parameters: {
      query?: never
      header?: {
        "X-CSRF-Token"?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  auth_get_current_user: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserResponse"]
        }
      }
    }
  }
  live_api_health_live_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HealthResponse"]
        }
      }
    }
  }
  ready_api_health_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReadinessReport"]
        }
      }
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReadinessReport"]
        }
      }
    }
  }
  list_visible_markets_api_markets_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MarketResponse"][]
        }
      }
    }
  }
  podcasts_list: {
    parameters: {
      query?: {
        locale?: "zh-hant" | "zh-hans" | "en"
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PodcastEpisodeSummaryResponse"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  podcasts_get: {
    parameters: {
      query?: {
        locale?: "zh-hant" | "zh-hans" | "en"
      }
      header?: never
      path: {
        episode_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PodcastEpisodeDetailResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  podcasts_create_audio_url: {
    parameters: {
      query?: {
        locale?: "zh-hant" | "zh-hans" | "en"
      }
      header?: never
      path: {
        episode_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PodcastAudioPlaybackResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  list_latest_reports_api_reports_get: {
    parameters: {
      query?: {
        locale?: "zh-hant" | "zh-hans" | "en"
        report_key?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReportSummaryResponse"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_latest_report_api_reports__market_code__latest_get: {
    parameters: {
      query?: {
        locale?: "zh-hant" | "zh-hans" | "en"
        report_key?: string
      }
      header?: never
      path: {
        market_code: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ReportDetailResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
}
